wordpress:
        image: wordpress
        links:
          -     wordpress_db:mysql
        ports:
          - 5080:80
wordpress_db:
        image: mariadb
        environment:
                MYSQL_ROOT_PASSWORD: edureka
phpmyadmin:
        image: corbinu/docker-phpmyadmin
        links:
          - wordpress_db:mysql
        ports:
            - 5088:80
        environment:
                MYSQL_USERNAME: root
                MYSQL_ROOT_PASSWORD: edureka
